---
- name: Virtual Machine Setup
  gather_facts: False
  hosts: elder_virtual_machine
  remote_user: fbabin
  become: yes
  vars:
    user: fbabin
    cluster: 3

  roles:
    - ssh_config
    - static_ip
  
  post_tasks:
    - name: restart vm
      command: reboot
      async: 1
      poll: 0
      ignore_errors: yes
...