---
- name: Virtual Machine Setup
  gather_facts: False
  hosts: virtual_machine
  remote_user: fbabin
  become: yes
  vars:
    user: fbabin

  tasks:
    - name: Wait for new target connection to become reachable/usable
      wait_for_connection:

...