---
- name: Add SSH key
  when: user is defined
  authorized_key: user={{ user }} key="{{ lookup('file', '~/.ssh/id_ecdsa.pub')}}"

- name: Change SSH port
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^Port'
    line="Port 54321"
    state=present
    backup=yes

- name: Allow PubkeyAuthentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PubkeyAuthentication'
    line="PubkeyAuthentication yes"
    state=present
    backup=yes

- name: Forbid Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PermitRootLogin'
    line="PermitRootLogin no"
    state=present
    backup=yes
