---
- name: Forbid Password Authentification
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PasswordAuthentication'
    line="PasswordAuthentication no"
    state=present
    backup=yes

- name: Forbid Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PermitRootLogin'
    line="PermitRootLogin no"
    state=present
    backup=yes

- name: Change SSH Port
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^Port'
    line="Port 54321"
    state=present
    backup=yes

- name: Allow PubkeyAuthentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PubkeyAuthentication'
    line="PubkeyAuthentication yes"
    state=present
    backup=yes
  notify:
    - restart ssh

- name: set ansible_ssh_port to default
  set_fact: ansible_ssh_port=54321